version: '3.1'

services:

  mongod:
    image: mongo
    container_name: "mongod"
    ports:
    - 27017:27017

  spring-server:
    image: imbipulkumar/task1javarestapiserver
    ports:
    - 8080:8080
    links:
    - mongod